name: Upload Python Package

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "ğŸ‰ Upload and Publish Python Package was automatically triggered by a ${{ github.event_name }} event."
      
      - run: echo "ğŸ§ Checkout the repository ..."
      - name: Checkout source
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
        
      - run: echo "ğŸ§ Setting up Python on the runner ..."
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: echo "ğŸ’¡ Python has been set up on the runner."
          
      echo "ğŸ§ Installing dependencies on the runner ..."
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - run: echo "ğŸ’¡ Dependencies have been installed on the runner."
          
      echo "ğŸ§ Building package on the runner ..."
      - name: Build package
        run: python -m build
      - run: echo "ğŸ’¡ Distribution has been build."
        
      echo "ğŸ§ Uploading package to PyPI ..."
      - name: Publish package to PyPI
        if: github.repository == 'VanNostrandLab/peak' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
